In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv("fake_or_real_news.csv",index_col=[0])

In [3]:
df.index.reindex(target=df.index,method='ReindexMethod')

(Index([ 8476, 10294,  3608, 10142,   875,  6903,  7341,    95,  4869,  2909,
        ...
         8411,  6143,  3262,  9337,  8737,  4490,  8062,  8622,  4021,  4330],
       dtype='int64', length=6335),
 None)

In [4]:
df.reset_index(inplace=True)

In [5]:
df.drop(columns=['index'],inplace=True)

In [6]:
lb = []
for i in df['label']:
    if i == 'FAKE':
        lb.append(0)
    else:
        lb.append(1)

In [7]:
lbl = np.array(lb)

In [8]:
df['label'] = lbl

In [9]:
df.head()

,title,text,label
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",0
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,0
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,1
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",0
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,1


In [10]:
x = df.drop('label',axis=1)

In [11]:
y = df['label']

In [12]:
x.shape,y.shape

((6335, 2), (6335,))

In [13]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [14]:
voc_size = 5000

In [15]:
msg = x.copy()

In [16]:
import nltk
import re
from nltk.corpus import stopwords

In [17]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [18]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

corpus = []

for i in range(0,len(msg)):
    review = re.sub('[^a-zA-Z]',' ',msg['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('English')]
    review = ' '.join(review)
    
    
    corpus.append(review)

In [19]:
len(corpus)

6335

In [20]:
one_hot_rep = [one_hot(words,voc_size) for words in corpus]
one_hot_rep

[[486, 1163, 1558],
 [1067, 3185, 4276, 4627, 2111, 344, 2529, 2739, 1243, 2563, 4657],
 [802, 3948, 1944, 2747, 3858],
 [1129, 185, 2798, 2607, 201, 2042, 1453, 3781],
 [4266, 2084, 2876, 504, 3290],
 [345, 3953],
 [4512, 378, 1067, 4012, 2216, 910],
 [2445, 1469, 213],
 [2125, 2105, 1243, 4076, 2170, 545, 3371],
 [4920, 1816, 3528, 2084, 4902, 2484, 2797, 2034, 1797],
 [80, 4076, 4629, 351, 1913, 1464, 1163, 4076, 3618],
 [4131, 1243, 1637, 2451, 4287, 463, 3098, 3387, 810, 2810],
 [1500, 4950, 788, 1941, 4182, 903, 1708, 2070, 4657],
 [3332, 700, 154, 550, 1205],
 [1243, 2727, 622, 2724],
 [1168, 1138, 586],
 [4361, 708, 2880, 1163, 1403, 828, 4586, 4390, 4336],
 [1163, 4076, 958, 3442, 700, 4160, 3502, 4734, 3085, 455, 2016, 4813, 1708],
 [4920, 1646, 2880, 2146],
 [4836, 2048, 4249, 3771, 4061, 2055, 700],
 [1329, 3839, 1243, 1787, 1875, 4180],
 [949, 765, 4612, 4187, 1223, 2714, 2660, 3715, 3374],
 [1163, 4076, 3528, 2993, 2757, 2695, 2820],
 [2084, 1426, 4388, 4246, 2231, 3342, 

# Embedding representation

.

In [22]:
sent_len = 10

embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=sent_len)

In [23]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,  486, 1163, 1558],
      dtype=int32)

In [24]:
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features))

model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.build(input_shape=(None, sent_len))
print(model.summary())


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 10, 40)              │         200,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ (None, 100)                 │          56,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │             101 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

None


In [25]:
len(embedded_docs),len(y)

(6335, 6335)

In [26]:
x_final = np.array(embedded_docs)
y_final = np.array(y)

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_final, y_final, test_size=0.33, random_state=42)

In [29]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=42)


Epoch 1/10
102/102 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.9859 - loss: 0.0383 - val_accuracy: 0.7360 - val_loss: 1.5406
Epoch 2/10
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.9950 - loss: 0.0181 - val_accuracy: 0.7226 - val_loss: 1.8291
Epoch 3/10
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.9948 - loss: 0.0167 - val_accuracy: 0.7322 - val_loss: 1.9138
Epoch 4/10
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.9964 - loss: 0.0094 - val_accuracy: 0.7379 - val_loss: 1.9548
Epoch 5/10
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.9986 - loss: 0.0053 - val_accuracy: 0.7374 - val_loss: 1.6795
Epoch 6/10
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.9954 - loss: 0.0164 - val_accuracy: 0.7245 - val_loss: 1.8335
Epoch 7/10
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.9974 - loss: 0.0129 - val_accuracy: 0.7360 - val_loss: 1.6769
Epoch 8/10
102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.9981 - loss: 0.0087 - val_accu

In [30]:
y_probs = model.predict(X_test)
y_pred = (y_probs > 0.5).astype(int)


66/66 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step


In [31]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [0]], shape=(2091, 1))

In [32]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [33]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.7317073170731707
Confusion Matrix:
 [[755 316]
 [245 775]]


In [34]:
model.save("model/model.h5")

In [40]:
df['text'][4]

'It\'s primary day in New York and front-runners Hillary Clinton and Donald Trump are leading in the polls.\n\nTrump is now vowing to win enough delegates to clinch the Republican nomination and prevent a contested convention. But Sens.Ted Cruz, R-Texas, Bernie Sanders, D-Vt., and Ohio Gov. John Kasich and aren\'t giving up just yet.\n\nA big win in New York could tip the scales for both the Republican and Democratic front-runners in this year\'s race for the White House. Clinton and Trump have each suffered losses in recent contests, shifting the momentum to their rivals.\n\n"We have won eight out of the last nine caucuses and primaries! Cheer!" Sanders recently told supporters.\n\nWhile wins in New York for Trump and Clinton are expected, the margins of those victories are also important.\n\nTrump needs to capture more than 50 percent of the vote statewide if he wants to be positioned to win all of the state\'s 95 GOP delegates. That would put him one step closer to avoiding a contes

In [ ]:
res = model.predictre()